export const exerciseLibrary = [
  {
    id: 'bench-press',
    name: 'Press de banca',
    category: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra,Banco',
    type: 'Hipertrofia',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 10,
    durationDefault: 60,
    image: './Barbell-Bench-Press.gif',
    instructions: [
      'Acuéstate en el banco con los pies apoyados y la espalda ligeramente arqueada.',
      'Desciende la barra controlando el movimiento hasta el pecho.',
      'Empuja la barra de vuelta sin perder el control de la zona lumbar.'
    ],
    tips: ['Mantén los omóplatos juntos.', 'No dejes que el codo se abra demasiado.'],
    warnings: ['Utiliza una técnica adecuada y progresa gradualmente.'],
    focus: 'Pecho'
  },
  {
    id: 'incline-press',
    name: 'Press inclinado',
    category: 'Pecho',
    secondaryMuscles: ['Hombros', 'Tríceps'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas,Banco',
    type: 'Hipertrofia',
    caloriesPerMinute: 7,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 50,
    image: './PRESINCLINADO.gif',
    instructions: ['Coloca el banco en un ángulo suave.', 'Haz el movimiento con control total.', 'No te impulses con el tronco.'],
    tips: ['Pisa el suelo para estabilizarte.', 'Controla la bajada para trabajar más tiempo el músculo.'],
    warnings: ['Detén el ejercicio si sientes dolor agudo o incomodidad.'],
    focus: 'Pecho'
  },
  {
    id: 'push-up',
    name: 'Flexiones normales',
    category: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros', 'Core'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Ninguno',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 45,
    image: './flexion.gif',
    instructions: ['Colócate en posición de plancha con manos a la altura del pecho.', 'Baja el cuerpo manteniendo la línea recta hasta que el pecho casi toque el suelo.', 'Empuja hacia arriba hasta la posición inicial con control.'],
    tips: ['Mantén el core activado y la cadera alineada.', 'Respira de forma controlada: inhala al bajar, exhala al subir.'],
    warnings: ['Evita arquear la zona lumbar; si hay dolor en muñecas, apoya los puños o usa manijas.'],
    focus: 'Pecho'
  },
  
    {
    id: 'dumbbell-fly',
    name: 'Aperturas con mancuernas',
    category: 'Pecho',
    secondaryMuscles: ['Hombros'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Mancuernas,Banco',
    type: 'Hipertrofia',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 42,
    image: './APERTURA CON MANCUERNAS.gif',
    instructions: ['Mantén los brazos ligeramente flexionados.', 'Abre las mancuernas con control.', 'Regresa con la misma trayectoria.'],
    tips: ['Evita exagerar el rango si sientes tensión en el hombro.', 'Haz una pausa corta al final del recorrido.'],
    warnings: ['No fuerces la espalda ni arquees la zona lumbar.'],
    focus: 'Pecho'
  },

  {
    id: 'diamond-pushup',
    name: 'Flexiones diamante con altura',
    category: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Peso corporal',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 40,
    image: './flexion de diamante con altura.gif',
    instructions: ['Coloca las manos juntas formando un diamante debajo del pecho.', 'Mantén el cuerpo recto desde la cabeza hasta los pies.', 'Baja con control hasta que el pecho casi toque las manos y sube explosivamente.'],
    tips: ['Mantén los codos cerca del torso para enfatizar los tríceps.', 'Activa el core para evitar hundir la cadera.'],
    warnings: ['Evita arquear la espalda; si hay dolor en muñecas, apoya sobre puños o realiza flexiones regulares.'],
    focus: 'Pecho'
  },

  {
    id: 'knee-to-chest-pushup',
    name: 'Flexiones con rodilla al pecho',
    category: 'Pecho',
    secondaryMuscles: ['Core', 'Tríceps', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Peso corporal',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 45,
    image: './01381301-Bottoms-Up-m_waist_720.gif',
    instructions: ['Colócate en posición de flexión con el cuerpo recto.', 'Realiza una flexión y al subir lleva una rodilla hacia el pecho.', 'Alterna la rodilla en cada repetición manteniendo la cadera estable.'],
    tips: ['Mantén el core activado para evitar que la cadera caiga.', 'Respira de forma controlada: inhala al bajar y exhala al subir y llevar la rodilla.'],
    warnings: ['Si sientes dolor en la zona lumbar, reduce el rango de movimiento o realiza flexiones estándar.'],
    focus: 'Pecho'
  },

  {
    id: 'dumbbell-front-raise',
    name: 'Elevación frontal con mancuernas',
    category: 'Hombros',
    secondaryMuscles: ['Trapecio superior', 'Pectoral clavicular', 'Serrato anterior'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Mancuernas',
    type: 'Fuerza',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 40,
    image: './Dumbbell-Front-Raise.gif',
    instructions: ['Párate con los pies a la anchura de los hombros y una mancuerna en cada mano.', 'Con los brazos ligeramente flexionados, eleva ambas mancuernas hacia delante hasta la altura de los hombros con control.', 'Baja lentamente sin dejar caer el peso y repite manteniendo el torso estable.'],
    tips: ['Usa un peso moderado para priorizar la técnica y evitar balanceo.', 'Mantén las muñecas neutras y el core activado para estabilizar la columna.'],
    warnings: ['Evita levantar más allá de la altura de los hombros para no sobrecargar la articulación del hombro.', 'Si tienes dolor en el hombro o historial de lesiones, consulta a un profesional y considera variantes con un solo brazo o movimientos más controlados.'],
    focus: 'Deltoides anterior'
  },

  
  {
    id: 'pull-up',
    name: 'Dominadas',
    category: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Antebrazos'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 7,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 55,
    image: './Dominadas.gif',
    instructions: ['Engánchate con la barra en agarre supino o prono.', 'Eleva el pecho hacia la barra.', 'Baja con control hasta extensión completa.'],
    tips: ['Piensa en empujar la tierra con los pies.', 'No balancees el cuerpo en la fase concéntrica.'],
    warnings: ['Si hay dolor en el hombro, reduce el rango.'],
    focus: 'Espalda'
  },
  {
    id: 'lat-pulldown',
    name: 'Jalón al pecho con polea',
    category: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Polea',
    type: 'Hipertrofia',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 10,
    durationDefault: 50,
    image: './Jalón al pecho.gif',
    instructions: ['Ajusta la almohadilla de la rodilla.', 'Tira de la polea hacia el pecho.', 'Mantén la espalda neutra durante el movimiento.'],
    tips: ['No desplomes los hombros.', 'Haz la bajada lenta para controlar el recorrido.'],
    warnings: ['Asegúrate de evitar encoger la espalda.'],
    focus: 'Espalda'
  },
  {
    id: 'bent-over-row',
    name: 'Remo inclinado con barra ',
    category: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Glúteos'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 58,
    image: './jdjdjdjdj.gif',
    instructions: ['Mantén la espalda neutra con una pequeña flexión de rodillas.', 'Tira del peso hacia el abdomen.', 'Baja de forma controlada.'],
    tips: ['Evita usar el impulso.', 'No giren el tronco mientras remas.'],
    warnings: ['Si sientes dolor lumbar, reduce la carga.'],
    focus: 'Espalda'
  },
    {
    id: 'bent-over-row',
    name: 'Remo inclinado con mancuernas ',
    category: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Glúteos'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 58,
    image: './Bent-Over-Dumbbell-Row.gif',
    instructions: ['Mantén la espalda neutra con una pequeña flexión de rodillas.', 'Tira del peso hacia el abdomen.', 'Baja de forma controlada.'],
    tips: ['Evita usar el impulso.', 'No giren el tronco mientras remas.'],
    warnings: ['Si sientes dolor lumbar, reduce la carga.'],
    focus: 'Espalda'
  },
  {
    id: 'barbell-curl',
    name: 'Curl con barra',
    category: 'Bíceps',
    secondaryMuscles: ['Antebrazos'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Barra',
    type: 'Hipertrofia',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 35,
    image: './Curl en Supinación con Barra.gif',
    instructions: ['Mantén codos pegados al cuerpo.', 'Eleva la barra con control.', 'Baja con una extensión completa del brazo.'],
    tips: ['Guarda el movimiento en un arco natural.', 'No te balancees hacia atrás.'],
    warnings: ['Ajusta la carga si hay tensión en la muñeca.'],
    focus: 'Bíceps'
  },
  {
    id: 'hammer-curl',
    name: 'Curl en Martillo Alterno con Mancuernas',
    category: 'Bíceps',
    secondaryMuscles: ['Antebrazos'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Mancuernas',
    type: 'Resistencia',
    caloriesPerMinute: 4,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 38,
    image: './Curl en Martillo Alterno con Mancuernas.gif',
    instructions: ['Mantén el agarre neutro.', 'Eleva las mancuernas sin mover el torso.', 'Controla la fase excéntrica.'],
    tips: ['Mantén hombros bajos y relajados.', 'Quita impulso para trabajar la fuerza de agarre.'],
    warnings: ['Siente la tensión en el bíceps y antebrazos, no en la espalda.'],
    focus: 'Bíceps'
  },
  {
    id: 'triceps-pushdown',
    name: 'Extensión de tríceps con polea',
    category: 'Tríceps',
    secondaryMuscles: ['Hombros'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Polea',
    type: 'Hipertrofia',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 36,
    image: './triceps-na-polia-alta.gif',
    instructions: ['Mantén los codos pegados a la cintura.', 'Extiende el brazo en un movimiento controlado.', 'Reduce la tensión sin permitir la desviación de codo.'],
    tips: ['No muevas el torso.', 'Haz una pausa breve al final del recorrido.'],
    warnings: ['Si hay dolor en el codo, disminuye la carga.'],
    focus: 'Tríceps'
  },
  {
    id: 'close-grip-press',
    name: 'Press cerrado con barra',
    category: 'Tríceps',
    secondaryMuscles: ['Pecho', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 48,
    image: './Press Cerrado con Barra.gif',
    instructions: ['Ajusta el agarre para que las manos queden próximas.', 'Baja la barra hasta el pecho.', 'Empuja con control sin bloquear de forma brusca.'],
    tips: ['Mantén el cuello largo y la espalda estable.', 'No desplaces la cabeza hacia adelante.'],
    warnings: ['No fuerces la técnica si notas tensión en hombros.'],
    focus: 'Tríceps'
  },
  {
    id: 'shoulder-press',
    name: 'Press Militar en Supinación con Mancuernas',
    category: 'Hombros',
    secondaryMuscles: ['Tríceps', 'Trapecios'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas',
    type: 'Fuerza',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 48,
    image: './Press Militar en Supinación con Mancuernas.gif',
    instructions: ['Mantén la barra a la altura de los hombros.', 'Empuja hacia arriba sin arquear la espalda.', 'Baja con control.'],
    tips: ['Activa el core antes del movimiento.', 'No bloquees la parte baja de la espalda.'],
    warnings: ['Haz la técnica con una carga adecuada a tu nivel.'],
    focus: 'Hombros'
  },
  {
    id: 'lateral-raise',
    name: 'Elevaciones laterales',
    category: 'Hombros',
    secondaryMuscles: ['Trapecios'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Mancuernas',
    type: 'Hipertrofia',
    caloriesPerMinute: 4,
    setsDefault: 3,
    repsDefault: 15,
    durationDefault: 35,
    image: './elevaciones laterales.gif',
    instructions: ['Eleva los brazos ligeramente por delante del cuerpo.', 'Llega hasta la altura de los hombros.', 'Baja con control.'],
    tips: ['Mantén la mirada hacia delante.', 'No uses el impulso con la espalda.'],
    warnings: ['Si notas dolor en la articulación del hombro, reduce el rango.'],
    focus: 'Hombros'
  },
  {
    id: 'squat',
    name: 'Sentadilla con mancuernas',
    category: 'Cuádriceps',
    secondaryMuscles: ['Glúteos', 'Pantorrillas'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 7,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 65,
    image: './Dumbbell-Jump-Squat.gif',
    instructions: ['Pisa el suelo con fuerza y mantén la espalda neutra.', 'Desciende con cadera hacia atrás.', 'Empuja hacia arriba con los talones.'],
    tips: ['Mantén la rodilla alineada con el segundo dedo del pie.', 'Mantén el pecho alto.'],
    warnings: ['Evita el desplazamiento hacia delante de la rodilla.'],
    focus: 'Piernas'
  },
  {
    id: 'trap-bar-jump-squat',
    name: 'Sentadilla con salto con trap bar',
    category: 'Cuádriceps',
    secondaryMuscles: ['Glúteos', 'Pantorrillas'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 8,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 60,
    image: './Trap-Bar-Jump-Squat.gif',
    instructions: ['Pisa el suelo con fuerza y mantén la espalda neutra.', 'Desciende con control y luego impulsa el cuerpo hacia arriba.', 'Haz el salto con fuerza sin perder la alineación corporal.'],
    tips: ['Mantén la rodilla alineada con el segundo dedo del pie.', 'Aterriza con suavidad para controlar el impacto.'],
    warnings: ['Evita la pérdida de control al aterrizar y reduce el rango si hay dolor en rodillas.'],
    focus: 'Piernas'
  },
  {
    id: 'incline-diamond-press',
    name: 'Press inclinado con agarre diamante',
    category: 'Pecho',
    secondaryMuscles: ['Hombros', 'Tríceps'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Hipertrofia',
    caloriesPerMinute: 7,
    setsDefault: 3,
    repsDefault: 8,
    durationDefault: 45,
    image: './PRESINCLINADO.gif',
    instructions: ['Ajusta el banco a un ángulo de 15° a 30° para enfatizar el pecho.', 'Coloca las manos juntas con agarre diamante y mantén los codos cerca del torso.', 'Baja la barra con control hasta la parte alta del pecho.', 'Empuja la barra hacia arriba sin arquear la espalda.'],
    tips: ['Mantén los omóplatos bajos y relajados.', 'No permitas que los codos se separen demasiado.', 'Respira al bajar y exhala al empujar.'],
    warnings: ['Detén el ejercicio si sientes dolor agudo en hombro o muñeca.', 'Evita impulsarte con el tronco.'],
    focus: 'Pecho'
  }, 
  {
    id: 'dumbbell-front-raise',
    name: 'Elevación frontal con mancuernas',
    category: 'Hombros',
    secondaryMuscles: ['Deltoides anterior'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Mancuernas',
    type: 'Hipertrofia',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 40,
    image: './Dumbbell-Front-Raise.gif',
    instructions: ['Mantén los brazos ligeramente extendidos y el torso quieto.', 'Eleva las mancuernas hacia delante hasta la altura de los hombros.', 'Baja con control sin balancear el cuerpo.'],
    tips: ['No uses impulso con la espalda ni con el torso.', 'Mantén la mirada al frente y los codos suaves.'],
    warnings: ['Reduce el rango si sientes dolor en el hombro o en la parte superior del brazo.'],
    focus: 'Hombros'
  },

  {
    id: 'barbell-bench-press',
    name: 'Press de banca con barra',
    category: 'Pecho',
    secondaryMuscles: ['Hombros', 'Tríceps'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 7,
    setsDefault: 4,
    repsDefault: 6,
    durationDefault: 55,
    image: './Barbell-Bench-Press.gif',
    instructions: ['Acuéstate en el banco con pies firmes en el suelo.', 'Coloca la barra con agarre cómodo y baja con control hasta el pecho.', 'Empuja la barra hacia arriba sin arquear la espalda.'],
    tips: ['Activa el core para mantener la espalda estable.', 'No dejes que la barra toque el cuello.'],
    warnings: ['Detén la serie si hay dolor agudo en hombro o muñeca.'],
    focus: 'Pecho'
  },
  {
    id: 'dumbbell-iron-cross',
    name: 'Iron cross con mancuernas',
    category: 'Pecho',
    secondaryMuscles: ['Hombros', 'Tríceps'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas',
    type: 'Hipertrofia',
    caloriesPerMinute: 6,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 45,
    image: './Dumbbell-Iron-Cross.gif',
    instructions: ['Mantén los brazos extendidos en un ángulo lateral desde el cuerpo.', 'Toma una mancuerna en cada mano y baja con control a los lados.', 'Vuelve a la posición inicial sin dejar que la espalda se desplace.'],
    tips: ['Mantén el pecho abierto y el core activo.', 'No dejes que los brazos se bloqueen al final.'],
    warnings: ['Si sientes dolor en el hombro, reduce la amplitud y evita el rango extremo.'],
    focus: 'Pecho'
  },
  {
    id: 'dumbbell-renegade-row',
    name: 'Remada renegade con mancuernas',
    category: 'Espalda',
    secondaryMuscles: ['Core', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas',
    type: 'Fuerza',
    caloriesPerMinute: 7,
    setsDefault: 3,
    repsDefault: 8,
    durationDefault: 50,
    image: './dumbbell-renegade-row-1.gif',
    instructions: ['Coloca dos mancuernas en el suelo en una posición de plancha.', 'Mantén el cuerpo estable y tira de una mancuerna hacia la cadera.', 'Baja con control y repite alternando lados.'],
    tips: ['Activa el core para estabilizar la posición.', 'Haz la remada con el codo cerca del cuerpo.'],
    warnings: ['Si se te mueve la pelvis o tienes dolor lumbar, baja la velocidad.'],
    focus: 'Espalda'
  },
  {
    id: 'planche-push-up',
    name: 'Flexion en plancha ',
    category: 'Core',
    secondaryMuscles: ['Pecho', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Avanzado',
    equipment: 'Ninguno',
    type: 'Fuerza',
    caloriesPerMinute: 8,
    setsDefault: 3,
    repsDefault: 5,
    durationDefault: 45,
    image: './Planche-Push-Up.gif',
    instructions: ['Situado en posición de plancha con hombros por encima de las manos.', 'Mantén el cuerpo en línea recta y empuja hacia arriba.', 'Baja lentamente hasta el suelo manteniendo la posición horizontal.'],
    tips: ['Activa glúteos y core para mantener la línea corporal.', 'Empieza con versiones más cortas para mejorar la estabilidad.'],
    warnings: ['Evita el ejercicio si tienes dolor de hombro o baja tolerancia a la carga isométrica.'],
    focus: 'Core'
  },
  {
    id: 'cross-body-plyometric',
    name: 'Flexión pliométrica cruzada',
    category: 'Core',
    secondaryMuscles: ['Hombros', 'Abdominales'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Ninguno',
    type: 'Pliometría',
    caloriesPerMinute: 9,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 35,
    image: './Cross-Body-Push-up_Plyometric.gif',
    instructions: ['Colócate en posición de plancha o en apoyo de manos.', 'Alterna la rodilla hacia el lado opuesto del codo con fuerza y control.', 'Mantén la cadera estable y el torso alineado durante todo el movimiento.'],
    tips: ['No levantes la cadera demasiado; busca estabilidad.', 'Haz la transición con la misma intensidad en ambos lados.'],
    warnings: ['Si tienes dolor lumbar o de muñeca, reduce la intensidad y la velocidad.'],
    focus: 'Core'
  },
  {
    id: 'dumbbell-jump-squat',
    name: 'Sentadilla con salto con mancuernas',
    category: 'Cuádriceps',
    secondaryMuscles: ['Glúteos', 'Pantorrillas'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Mancuernas',
    type: 'Pliometría',
    caloriesPerMinute: 8,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 50,
    image: './Dumbbell-Jump-Squat.gif',
    instructions: ['Sostén una mancuerna en cada mano con torso erguido.', 'Desciende en sentadilla con control y luego impulsa el cuerpo hacia arriba.', 'Haz el salto sin perder la alineación de rodillas y cadera.', 'Aterriza con suavidad y vuelve a la posición inicial.'],
    tips: ['Mantén la mirada al frente y la espalda neutra.', 'Aterriza con los talones y controla la flexión de rodillas.'],
    warnings: ['Evita saltos altos si sientes dolor en rodillas o si pierdes control al aterrizar.'],
    focus: 'Piernas'
  },
  {
    id: 'push-up-toe-touch',
    name: 'Flexion con toque de pie',
    category: 'Core',
    secondaryMuscles: ['Pecho', 'Hombros'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Ninguno',
    type: 'Condición',
    caloriesPerMinute: 8,
    setsDefault: 3,
    repsDefault: 10,
    durationDefault: 40,
    image: './Push-Up-Toe-Touch.gif',
    instructions: ['Colócate en posición de flexiones de pecho con cuerpo alineado.', 'Al subir, lleva una pierna hacia adelante para tocar la mano opuesta.', 'Regresa con control a la posición de apoyo.'],
    tips: ['Controla el movimiento para mantener el equilibrio.', 'No dejes que la cadera se balancee.'],
    warnings: ['Si notas dolor de muñeca o espalda baja, reduce la velocidad y el rango.'],
    focus: 'Core'
  },
  {
    id: 'romanian-deadlift',
    name: 'Peso muerto rumano con mancuernas',
    category: 'Isquiotibiales',
    secondaryMuscles: ['Glúteos', 'Espalda'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Fuerza',
    caloriesPerMinute: 7,
    setsDefault: 4,
    repsDefault: 8,
    durationDefault: 60,
    image: './dumbbell-deadlifts.gif',
    instructions: ['Mantén la espalda neutral con una ligera flexión de rodillas.', 'Baja la barra controlando la cadera.', 'Vuelve a la posición inicial con fuerza.'],
    tips: ['No redondees la espalda.', 'Los glúteos deben liderar el movimiento.'],
    warnings: ['Detén el ejercicio si hay dolor lumbar agudo.'],
    focus: 'Piernas'
  },
  {
    id: 'lunge',
    name: 'Zancadas',
    category: 'Piernas',
    secondaryMuscles: ['Glúteos', 'Cuádriceps'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Peso corporal',
    type: 'Resistencia',
    caloriesPerMinute: 6,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 45,
    image: './dumbbell-lunges.gif',
    instructions: ['Avanza con una pierna y baja hasta un ángulo cómodo.', 'Vuelve al centro con control.', 'Mantén el tronco vertical.'],
    tips: ['Haz el movimiento con una mirada fija.', 'Alterna lados con la misma cadencia.'],
    warnings: ['Si se te desequilibra, reduce la amplitud.'],
    focus: 'Piernas'
  },
  {
    id: 'hip-thrust',
    name: 'Hip thrust',
    category: 'Glúteos',
    secondaryMuscles: ['Isquiotibiales'],
    gender: 'women',
    difficulty: 'Intermedio',
    equipment: 'Barra',
    type: 'Hipertrofia',
    caloriesPerMinute: 6,
    setsDefault: 4,
    repsDefault: 10,
    durationDefault: 50,
    image: './hip-thrust2.gif',
    instructions: ['Apoya la espalda en el banco con la barra sobre la cadera.', 'Eleva la cadera al máximo.', 'Baja lentamente y repite.'],
    tips: ['Activa glúteos desde la parte superior del movimiento.', 'No empujes con la zona lumbar.'],
    warnings: ['Mantén el cuello en línea con la columna para evitar tensión.'],
    focus: 'Glúteos'
  },
  {
    id: 'plank',
    name: 'Plancha',
    category: 'Abdomen',
    secondaryMuscles: ['Glúteos', 'Espalda'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Sin equipamiento',
    type: 'Core',
    caloriesPerMinute: 5,
    setsDefault: 3,
    repsDefault: 1,
    durationDefault: 45,
    image: './body-saw-plank.gif',
    instructions: ['Apoya antebrazos o manos y mantén la línea corporal.', 'Contrae el core sin arquear la espalda.', 'Mantén la respiración controlada.'],
    tips: ['Activa glúteos para estabilidad.', 'No dejes que la cadera se hunde.'],
    warnings: ['Detén el ejercicio si aparece dolor lumbar o mareo.'],
    focus: 'Core'
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'Abdomen',
    secondaryMuscles: ['Oblicuos'],
    gender: 'unisex',
    difficulty: 'Principiante',
    equipment: 'Sin equipamiento',
    type: 'Core',
    caloriesPerMinute: 4,
    setsDefault: 3,
    repsDefault: 15,
    durationDefault: 30,
    image: './CRUNCH.gif',
    instructions: ['Siéntate con la espalda en el suelo y las rodillas flexionadas.', 'Eleva los hombros con fuerza del abdomen.', 'Baja con control.'],
    tips: ['Piensa en enrollar la columna.', 'No uses las manos para tirar del cuello.'],
    warnings: ['Si hay dolor cervical, reduce el rango.'],
    focus: 'Core'
  },
  {
    id: 'mountain-climber',
    name: 'Mountain climbers',
    category: 'Abdomen',
    secondaryMuscles: ['Hombros', 'Glúteos'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Peso corporal',
    type: 'Cardio',
    caloriesPerMinute: 8,
    setsDefault: 3,
    repsDefault: 20,
    durationDefault: 45,
    image: './moutan climbers.gif',
    instructions: ['Partiendo en plancha alta, lleva una rodilla al pecho.', 'Alterna piernas con ritmo sostenido.', 'Mantén el torso estable.'],
    tips: ['No abras la cadera ni te inclines demasiado.', 'Usa una cadencia constante y respiración controlada.'],
    warnings: ['Si sientes mareo, reduce la intensidad.'],
    focus: 'Cardio'
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'Cuerpo completo',
    secondaryMuscles: ['Piernas', 'Hombros', 'Core'],
    gender: 'unisex',
    difficulty: 'Intermedio',
    equipment: 'Peso corporal',
    type: 'Cardio',
    caloriesPerMinute: 9,
    setsDefault: 3,
    repsDefault: 12,
    durationDefault: 50,
    image: './burpees.gif',
    instructions: ['Baja a plancha y empuja para volver arriba.', 'Añade un salto final al levantarte.', 'Mantén el ritmo controlado.'],
    tips: ['No pierdas el centro del cuerpo.', 'Si el impacto es alto, reduce la altura del salto.'],
    warnings: ['Utiliza una técnica segura y toma pausas si hay fatiga.'],
    focus: 'Cardio'
  }
];

export const categoryMeta = {
  Pecho: { accent: '#ff7a59' },
  Espalda: { accent: '#5aa9ff' },
  Bíceps: { accent: '#8d7ef2' },
  Tríceps: { accent: '#3ecf99' },
  Hombros: { accent: '#f4b942' },
  Antebrazos: { accent: '#ffb1c1' },
  Abdomen: { accent: '#3bc9ad' },
  Glúteos: { accent: '#d97706' },
  Cuádriceps: { accent: '#62c9ff' },
  Isquiotibiales: { accent: '#7f9cf5' },
  Pantorrillas: { accent: '#a78bfa' },
  Piernas: { accent: '#ef4444' },
  'Cuerpo completo': { accent: '#10b981' },
  Cardio: { accent: '#f97316' }
};

export const filters = {
  levels: ['Principiante', 'Intermedio', 'Avanzado'],
  equipment: ['Peso corporal', 'Mancuernas', 'Barra', 'Máquina', 'Polea', 'Bandas', 'Kettlebell', 'Banco', 'Sin equipamiento'],
  types: ['Fuerza', 'Hipertrofia', 'Resistencia', 'Cardio', 'Movilidad', 'Core'],
  genders: ['Hombres', 'Mujeres', 'Unisex']
};
